### ISSUE TITLE
[NFR] sql export function

### ISSUE THREAD

**Issue by ruudboon** [phalcon/migrations#25]
Sometimes it can be useful to have an export function to export a schema. 
A use case could be using your migrations for your testing framework. 
To setup the database for the test you want to import an sql dump. It would be great if migrations can export the latest schema without the need to run all the migrations from version 1.

For example:
```php
vendor/bin/phalcon-migrations migrations export 
```
Will output a full sql dump of the latest migration. For example this could be used with Codeception in the following way.

```
modules:
   enabled:
      - Db:
         dsn: 'mysql:host=localhost;dbname=testdb'
         user: 'root'
         password: ''
         populate: true # run populator before all tests
         cleanup: true # run populator before each test
         populator: 'mysql -u $user -h $host $dbname < `vendor/bin/phalcon-migrations migrations export `'
```
Or save a specific version (1.2.1) like
```
vendor/bin/phalcon-migrations migrations export 1.2.1  > export.sql
```
